
brew cask install appcleaner
brew cask install audacity
brew cask install chicken
brew cask install cyberduck
brew cask install dash
brew cask install dropbox
brew cask install docker
brew cask install evernote
brew cask install firefox
brew cask install freemind
brew cask install gimp
brew cask install google-chrome
brew cask install google-earth
brew cask install googleappengine
brew cask install gpgtools
brew cask install intellij-idea
brew cask install istat-menus
brew cask install iterm2
brew cask install knuff
brew cask install libreoffice
brew cask install mailplane
brew cask install opera
brew cask install skype
brew cask install sublime-text
brew cask install timemachineeditor
brew cask install tunnelblick
brew cask install viber
brew cask install vienna
brew cask install vine-server
brew cask install vlc
brew cask install java
brew cask install lunchrocket
brew cask install xquartz
brew cask install flour
