# brew completion
if [[ `uname` == 'Darwin' ]]; then
    fpath=(/usr/local/share/zsh-completions $fpath)
fi


# ZSH SETTINGS
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="simplex"
SKIPED_USERNAMES=(nikita n.kovalev nkovalev)

# case-sensitive completion.
CASE_SENSITIVE="true"

# how often to auto-update (in days).
export UPDATE_ZSH_DAYS=7
DISABLE_AUTO_UPDATE=true

# disable auto-setting terminal title.
#DISABLE_AUTO_TITLE="true"

# enable command auto-correction.
#ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"


ZSH_CUSTOM="$HOME/Dev/dev-setup/zsh/oh-my-zsh_custom"


# PLUGINS SETUP

export DISABLE_VENV_CD=1

plugins=(lightgit cdd virtualenv virtualenvwrapper pip f sbt-no-alias scala)

# HOSTSPECIFIC SETUP

if [ -f ~/.zshrc-local ]; then
    source ~/.zshrc-local
fi


# LAUNCH OH MY ZSH
source $ZSH/oh-my-zsh.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
