
# brew completion
if [[ `uname` == 'Darwin' ]]; then
    fpath=(/usr/local/share/zsh-completions $fpath)
fi


# ZSH SETTINGS
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="eastwood"

# case-sensitive completion.
CASE_SENSITIVE="true"

# how often to auto-update (in days).
export UPDATE_ZSH_DAYS=7

# disable auto-setting terminal title.
#DISABLE_AUTO_TITLE="true"

# enable command auto-correction.
#ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"


ZSH_CUSTOM="$HOME/Dev/dev-setup/zsh/oh-my-zsh_custom"


# PLUGINS SETUP

export DISABLE_VENV_CD=1

plugins=(lightgit cdd virtualenvwrapper)


# LAUNCH OH MY ZSH
source $ZSH/oh-my-zsh.sh
