#!/bin/bash
# Clean *.pyc files

echo "Are you sure to clean *.pyc files from ${PWD} ? [n/Y]"

read ACK
if [[ $ACK == "Y" || $ACK == "y" || $ACK == "" ]]; then
	find ./ -iname '*.pyc' -exec rm {} \;

fi
